/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_WindowsDirectInputDevice3 */

#ifndef _Included_org_lwjgl_opengl_WindowsDirectInputDevice3
#define _Included_org_lwjgl_opengl_WindowsDirectInputDevice3
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_EXCLUSIVE
#define org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_EXCLUSIVE 1L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_NONEXCLUSIVE
#define org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_NONEXCLUSIVE 2L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_FOREGROUND
#define org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_FOREGROUND 4L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_BACKGROUND
#define org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_BACKGROUND 8L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_NOWINKEY
#define org_lwjgl_opengl_WindowsDirectInputDevice3_DISCL_NOWINKEY 16L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_XAxis
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_XAxis 1L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_YAxis
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_YAxis 2L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_ZAxis
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_ZAxis 3L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Button
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Button 4L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Unknown
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Unknown 5L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_DATA_SIZE
#define org_lwjgl_opengl_WindowsDirectInputDevice3_DATA_SIZE 3L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_XAxis
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_XAxis 1L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_YAxis
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_YAxis 2L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_ZAxis
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_ZAxis 3L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Button
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Button 4L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Unknown
#define org_lwjgl_opengl_WindowsDirectInputDevice3_GUID_Unknown 5L
#undef org_lwjgl_opengl_WindowsDirectInputDevice3_DATA_SIZE
#define org_lwjgl_opengl_WindowsDirectInputDevice3_DATA_SIZE 3L
/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    setDataFormat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_setDataFormat
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    setCooperativeLevel
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_setCooperativeLevel
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    acquire
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_acquire
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    getDeviceState
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_getDeviceState
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    getDeviceData
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/IntBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_getDeviceData
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    unacquire
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_unacquire
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    setBufferSize
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_setBufferSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    getEventSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_getEventSize
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInputDevice3
 * Method:    enumObjects
 * Signature: (JLorg/lwjgl/opengl/WindowsDirectInputDeviceObjectCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDirectInputDevice3_enumObjects
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
