/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_WindowsDirectInput8 */

#ifndef _Included_org_lwjgl_opengl_WindowsDirectInput8
#define _Included_org_lwjgl_opengl_WindowsDirectInput8
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_WindowsDirectInput8_KEYBOARD_TYPE
#define org_lwjgl_opengl_WindowsDirectInput8_KEYBOARD_TYPE 1L
#undef org_lwjgl_opengl_WindowsDirectInput8_MOUSE_TYPE
#define org_lwjgl_opengl_WindowsDirectInput8_MOUSE_TYPE 2L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_OK
#define org_lwjgl_opengl_WindowsDirectInput8_DI_OK 0L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_NOEFFECT
#define org_lwjgl_opengl_WindowsDirectInput8_DI_NOEFFECT 1L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_PROPNOEFFECT
#define org_lwjgl_opengl_WindowsDirectInput8_DI_PROPNOEFFECT 1L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_POLLEDDEVICE
#define org_lwjgl_opengl_WindowsDirectInput8_DI_POLLEDDEVICE 2L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_DOWNLOADSKIPPED
#define org_lwjgl_opengl_WindowsDirectInput8_DI_DOWNLOADSKIPPED 3L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_EFFECTRESTARTED
#define org_lwjgl_opengl_WindowsDirectInput8_DI_EFFECTRESTARTED 4L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_TRUNCATED
#define org_lwjgl_opengl_WindowsDirectInput8_DI_TRUNCATED 8L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_SETTINGSNOTSAVED
#define org_lwjgl_opengl_WindowsDirectInput8_DI_SETTINGSNOTSAVED 11L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_TRUNCATEDANDRESTARTED
#define org_lwjgl_opengl_WindowsDirectInput8_DI_TRUNCATEDANDRESTARTED 12L
#undef org_lwjgl_opengl_WindowsDirectInput8_DI_BUFFEROVERFLOW
#define org_lwjgl_opengl_WindowsDirectInput8_DI_BUFFEROVERFLOW 1L
#undef org_lwjgl_opengl_WindowsDirectInput8_DIERR_INPUTLOST
#define org_lwjgl_opengl_WindowsDirectInput8_DIERR_INPUTLOST -2147024866L
#undef org_lwjgl_opengl_WindowsDirectInput8_DIERR_NOTACQUIRED
#define org_lwjgl_opengl_WindowsDirectInput8_DIERR_NOTACQUIRED -2147024868L
#undef org_lwjgl_opengl_WindowsDirectInput8_DIERR_OTHERAPPHASPRIO
#define org_lwjgl_opengl_WindowsDirectInput8_DIERR_OTHERAPPHASPRIO -2147024891L
#undef org_lwjgl_opengl_WindowsDirectInput8_KEYBOARD_TYPE
#define org_lwjgl_opengl_WindowsDirectInput8_KEYBOARD_TYPE 1L
#undef org_lwjgl_opengl_WindowsDirectInput8_MOUSE_TYPE
#define org_lwjgl_opengl_WindowsDirectInput8_MOUSE_TYPE 2L
/*
 * Class:     org_lwjgl_opengl_WindowsDirectInput8
 * Method:    createDirectInput
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_WindowsDirectInput8_createDirectInput
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInput8
 * Method:    nCreateDevice
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_WindowsDirectInput8_nCreateDevice
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDirectInput8
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDirectInput8_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
