/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_WindowsAWTInput */

#ifndef _Included_org_lwjgl_opengl_WindowsAWTInput
#define _Included_org_lwjgl_opengl_WindowsAWTInput
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_WindowsAWTInput_WS_CHILD
#define org_lwjgl_opengl_WindowsAWTInput_WS_CHILD 1073741824L
/*
 * Class:     org_lwjgl_opengl_WindowsAWTInput
 * Method:    getWindowStyles
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsAWTInput_getWindowStyles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsAWTInput
 * Method:    getParentWindow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_WindowsAWTInput_getParentWindow
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
